spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/api_rlRefractor
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: on
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
#  server:
#    port: 80
#    context-path: /webui